### ISSUE TITLE
Flux v2

### ISSUE THREAD

**Issue by stefanprodan** [JimPruitt/chocolatey-packages#6]
Hey Jim, first I want to say thanks for maintaining the fluxctl package!

For over a year now we've been working on Flux v2 that comes with a CLI named simply `flux`. The Windows binaries are available at https://github.com/fluxcd/flux2/releases

Are you ok to add the v2 CLI to your repo and submit it to Chocolatey under the `flux` name?

**Comment by JimPruitt** [comment]
Will do.  I'll have it submitted by EOD today.Sent from my Galaxy
-------- Original message --------From: Stefan Prodan ***@***.***> Date: 7/2/21  8:39 AM  (GMT-05:00) To: JimPruitt/chocolatey-packages ***@***.***> Cc: Subscribed ***@***.***> Subject: [JimPruitt/chocolatey-packages] Flux v2 (#6) 
Hey Jim, first I want to say thanks for maintaining the fluxctl package!
For over a year now we've been working on Flux v2 that comes with a CLI named simply flux. The Windows binaries are available at https://github.com/fluxcd/flux2/releases
Are you ok to add the v2 CLI to your repo and submit it to Chocolatey under the flux name?

**Comment by JimPruitt** [comment]
Just a follow up on this.   Flux2 has indeed been submitted to Chocolatey.org as 'flux'. I wasn't immediately sure how to add chocolatey support for 'amd' based architectures.  I will keep this issue open until the package gets approved by the moderators.

**Comment by JimPruitt** [comment]
Closing this issue as Flux2 0.16.0 has been approved and is available here https://community.chocolatey.org/packages/flux.
